2023-11-06 20:54:20,272 - basicLogger - INFO - MySQL database hostname: acit3855group45kafka.eastus2.cloudapp.azure.com, port: 3306
2023-11-06 20:54:21,691 - basicLogger - INFO - Connecting to Kafka...
2023-11-06 20:54:22,019 - basicLogger - INFO - Connected to Kafka.
2023-11-06 20:54:22,645 - basicLogger - ERROR - Error in process_messages: 
Traceback (most recent call last):
  File "C:\Users\eddie\Desktop\acit3855microservice\storage\app.py", line 47, in process_messages
    topic = client.topics[str.encode(app_config["events"]["topic"])]
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python310\lib\site-packages\pykafka\cluster.py", line 74, in __getitem__
    topic = Topic(self._cluster(), meta.topics[key])
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python310\lib\site-packages\pykafka\topic.py", line 67, in __init__
    self.update(topic_metadata)
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python310\lib\site-packages\pykafka\topic.py", line 230, in update
    raise LeaderNotFoundError()
pykafka.exceptions.LeaderNotFoundError
2023-11-06 20:54:36,521 - basicLogger - INFO - MySQL database hostname: acit3855group45kafka.eastus2.cloudapp.azure.com, port: 3306
2023-11-06 20:54:38,081 - basicLogger - INFO - Connecting to Kafka...
2023-11-06 20:54:38,370 - basicLogger - INFO - Connected to Kafka.
2023-11-06 20:54:38,926 - basicLogger - ERROR - Error in process_messages: 
Traceback (most recent call last):
  File "C:\Users\eddie\Desktop\acit3855microservice\storage\app.py", line 47, in process_messages
    topic = client.topics[str.encode(app_config["events"]["topic"])]
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python310\lib\site-packages\pykafka\cluster.py", line 74, in __getitem__
    topic = Topic(self._cluster(), meta.topics[key])
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python310\lib\site-packages\pykafka\topic.py", line 67, in __init__
    self.update(topic_metadata)
  File "C:\Users\eddie\AppData\Local\Programs\Python\Python310\lib\site-packages\pykafka\topic.py", line 230, in update
    raise LeaderNotFoundError()
pykafka.exceptions.LeaderNotFoundError
2023-11-06 22:10:06,146 - basicLogger - INFO - MySQL database hostname: acit3855group45kafka.eastus2.cloudapp.azure.com, port: 3306
2023-11-06 22:10:26,204 - basicLogger - INFO - MySQL database hostname: acit3855group45kafka.eastus2.cloudapp.azure.com, port: 3306
2023-11-06 22:10:27,656 - basicLogger - INFO - Connecting to Kafka...
2023-11-06 22:10:28,227 - basicLogger - INFO - Connected to Kafka.
2023-11-06 22:10:32,590 - basicLogger - INFO - Consumer created. Listening for messages on topic: events
